sudo: required
language: node_js
node_js:
  - "6.10"

before_deploy:
  - pip install --user awscli
  - npm install -g serverless
  - aws s3 cp s3://tw-config/config.js ./config.js --region ap-northeast-2
  - git add config.js
  - git commit -m "update release-config.js"

deploy:
  provider: script
  script:
    - sls deploy -v
    - npm run e2etest
  on:
    branch: master
