sudo: required
language: node_js
node_js:
  - "6.10"
cache:
  directories:
    - node_modules

before_deploy:
  - pip install --user awscli
  - npm install -g serverless
  - aws s3 cp s3://tw-config/config.js ./config.js --region ap-northeast-2
  - git add config.js
  - git commit -m "update release-config.js"
  - npm install --only=production

after_deploy:
  - npm run e2etest

deploy:
  - provider: script
    script:
      - sls deploy -v
    on:
      branch: master
